version: "3.0"

services:
  ergo:
    build: .
    volumes:
    - .:/app
    ports:
      - "3032:3032"
      - "3256:3256"
    restart: always
    networks:
      - ergo-pool

networks:
  ergo-pool:
    driver: bridge
